#Location.create(locale:"NYC")
#Location.create(locale:"Los Angeles")
#Location.create(locale:"Las Vegas")
#Location.create(locale:"Miami")
#Location.create(locale:"San Francisco")
#Location.create(locale:"Arlington")
#Location.create(locale:"Dallas")
#Location.create(locale:"MSG")
#Location.create(locale:"Barcalys Center")
Category.create(name: "Music")
Category.create(name: "Soccer")
Category.create(name: "Baseball")
Category.create(name: "Tennis")
Category.create(name: "Basketball")
Category.create(name: "Football")
